//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class destination
    {
        public int id { get; set; }
        public string dname { get; set; }
        public string dtime { get; set; }
        public string location { get; set; }
        public string description { get; set; }
        public string photo { get; set; }
    }
}
